#! /bin/sh
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:wa --update-oa 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:ca --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US West - CA
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:ak us:hi us:mt us:ut us:nv us:az us:nm us:wy us:wa us:or us:id us:co --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US Midwest
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:nd us:sd us:ne us:ks us:mn us:ia us:mo us:wi us:mi us:il us:in us:ky us:oh --update-osm --load-oa --filter-data --output-osm --quality-check;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US South - tx 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:ok us:ar us:la us:tn us:al us:ms us:ga us:nc us:sc --update-osm --load-oa --filter-data --output-osm --quality-check;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US NE skipping ma 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:dc us:va us:wv us:md us:de us:pa us:nj us:ct us:ri us:nh us:vt us:me us:ny --update-osm --load-oa --filter-data --output-osm --quality-check;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:fl --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:tx --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py us:pr --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# rsync us to server
cd /home/pat/projects/osmand_map_creation/osmand_obf/;rsync -t *.obf root@205.185.118.244:/var/www/html/opensupermaps/static/downloads/ 
# CA nl failed
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py ca:nb ca:pe ca:ns ca:nl ca:yt ca:nt ca:nt --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py ca:ab ca:mb ca:sk --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py ca:bc --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py ca:on --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py ca:qc --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_obf/;rsync -t *.obf root@205.185.118.244:/var/www/html/opensupermaps/static/downloads/ 
# MX
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py mx --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# carribean
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing_worldwide.py jm --update-osm --load-oa --filter-data --output-osm --quality-check --slice;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_obf/;rsync -t *.obf root@205.185.118.244:/var/www/html/opensupermaps/static/downloads/ 
# command > log.txt 2>&1 log python code to file?
