#! /bin/sh
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:wa --update-oa 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:ca --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US West - CA
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:ak us:hi us:mt us:ut us:nv us:az us:nm us:wy us:wa us:or us:id us:co --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US Midwest
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:nd us:sd us:ne us:ks us:mn us:ia us:mo us:wi us:mi us:il us:in us:ky us:oh --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US South - tx 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:ok us:ar us:la us:tn us:al us:ms us:ga us:nc us:sc --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# US NE skipping ma 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:dc us:va us:wv us:md us:de us:pa us:nj us:ct us:ri us:nh us:vt us:me us:ny --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:fl --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:tx --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py us:pr --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# rsync us to server
cd /home/pat/projects/osmand_map_creation/osmand_obf/;rsync -t *.obf root@205.185.118.244:/var/www/html/opensupermaps/static/downloads/ 
# CA nl failed
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py ca:nb ca:pe ca:ns ca:nl ca:yt ca:nt ca:nt --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py ca:ab ca:mb ca:sk --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py ca:bc --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py ca:on --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py ca:qc --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_obf/;rsync -t *.obf root@205.185.118.244:/var/www/html/opensupermaps/static/downloads/ 
# MX
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py mx --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
# carribean
cd /home/pat/projects/osmand_map_creation/osmand_osm/osm/;python3 processing.py jm --normal;cd /home/pat/projects/osmand_map_creation/;java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx22G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.util.IndexBatchCreator batch.xml;cd /home/pat/projects/osmand_map_creation/osmand_osm;mv *.pbf osm/ 
cd /home/pat/projects/osmand_map_creation/osmand_obf/;rsync -t *.obf root@205.185.118.244:/var/www/html/opensupermaps/static/downloads/ 
# command > log.txt 2>&1 log python code to file?
